# Build Windows 11 gaming template

build:
    packer build -var-file="../../variables.pkrvars.hcl" windows11-gaming.pkr.hcl

validate:
    packer validate -var-file="../../variables.pkrvars.hcl" windows11-gaming.pkr.hcl

fmt:
    packer fmt windows11-gaming.pkr.hcl
